#!/bin/sh

# Find the top of the workspace regardless of where this script was
# started from
SCRIPT_DIR=`dirname $0`
START_DIR=`pwd`
REL_PATH_TO_WS="../../.."
WS_DIR=`cd ${START_DIR}/${SCRIPT_DIR}/${REL_PATH_TO_WS} && pwd`

# The local user's maven repository from which the required libs will
# be found
REPO_DIR=${HOME}/.m2/repository

REQ_PROJECTS="trigger \
juggler \
payload \
splicer \
daq-io \
daq-common \
daq-log"

REQ_LIBS="commons-logging \
log4j \
jaxp-ri jaxp-api \
jaxb-xjc jaxb-impl jaxb-libs jaxb-api \
jax-qname relaxng xsdlib \
xmlrpc-common \
xmlrpc-client \
xmlrpc-server \
icebucket \
concurrent \
ws-commons-util \
jmxtools"

missing_jar=
CLASSPATH=""
for proj in ${REQ_PROJECTS}; do
  jar=${WS_DIR}/${proj}/target/${proj}-${pom.version}.jar
  if [ -f "$jar" ]; then
    CLASSPATH=${jar}:${CLASSPATH}
  else
    echo "$0: Cannot find ${proj} jar file" >&2
    missing_jar=true
  fi
done

for lib in ${REQ_LIBS}; do
  jar=
  for i in `find ${REPO_DIR} -name ${lib}\*.jar`; do
    jar="$i"
  done
  if [ -f "$jar" ]; then
    CLASSPATH=$jar:${CLASSPATH}
  else
    echo "$0: Cannot find ${lib} jar file" >&2
    missing_jar=true
  fi
done

if [ ! -z ${missing_jar} ]; then
  exit 1
fi

export CLASSPATH
#echo "CLASSPATH=${CLASSPATH}"
java -Xmx1024m icecube.daq.trigger.component.AmandaTriggerComponent $@
